package FrontEndApp;

/**
* FrontEndApp/FrontEndServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Java/EclipseWorkspace/COMP6231_Project/FrontEnd.idl
* Monday, March 16, 2020 7:27:45 PM EDT
*/

public final class FrontEndServerHolder implements org.omg.CORBA.portable.Streamable
{
  public FrontEndApp.FrontEndServer value = null;

  public FrontEndServerHolder ()
  {
  }

  public FrontEndServerHolder (FrontEndApp.FrontEndServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FrontEndApp.FrontEndServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FrontEndApp.FrontEndServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FrontEndApp.FrontEndServerHelper.type ();
  }

}
