package EventApp03;


/**
* EventApp03/EventServer03.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Java/EclipseWorkspace/COMP6231_Project/Event03.idl
* Thursday, March 19, 2020 10:28:00 AM EDT
*/

public interface EventServer03 extends EventServer03Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EventServer03
