package EventApp;


/**
* EventApp/EventServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Java/EclipseWorkspace/COMP6231_Project/Event.idl
* Wednesday, March 25, 2020 5:36:11 PM EDT
*/

abstract public class EventServerHelper
{
  private static String  _id = "IDL:EventApp/EventServer:1.0";

  public static void insert (org.omg.CORBA.Any a, EventApp.EventServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EventApp.EventServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EventApp.EventServerHelper.id (), "EventServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EventApp.EventServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EventServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EventApp.EventServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EventApp.EventServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EventApp.EventServer)
      return (EventApp.EventServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EventApp._EventServerStub stub = new EventApp._EventServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static EventApp.EventServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EventApp.EventServer)
      return (EventApp.EventServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EventApp._EventServerStub stub = new EventApp._EventServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
