package EventApp;


/**
* EventApp/EventServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Java/EclipseWorkspace/COMP6231_Project/Event.idl
* Wednesday, March 25, 2020 5:36:11 PM EDT
*/

public interface EventServer extends EventServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EventServer
