package EventApp;

/**
* EventApp/EventServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Java/EclipseWorkspace/COMP6231_Project/Event.idl
* Wednesday, March 25, 2020 5:36:11 PM EDT
*/

public final class EventServerHolder implements org.omg.CORBA.portable.Streamable
{
  public EventApp.EventServer value = null;

  public EventServerHolder ()
  {
  }

  public EventServerHolder (EventApp.EventServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EventApp.EventServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EventApp.EventServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EventApp.EventServerHelper.type ();
  }

}
