package FrontEndApp;


/**
* FrontEndApp/FrontEndServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Java/EclipseWorkspace/COMP6231_Project/FrontEnd.idl
* Tuesday, April 7, 2020 2:12:00 PM EDT
*/

public interface FrontEndServerOperations 
{
  String sendtoFE (String message);
  void shutdown ();
} // interface FrontEndServerOperations
