package EventApp02;


/**
* EventApp02/EventServer02Helper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Java/EclipseWorkspace/COMP6231_Project/Event03.idl
* Thursday, March 19, 2020 10:27:37 AM EDT
*/

abstract public class EventServer02Helper
{
  private static String  _id = "IDL:EventApp02/EventServer02:1.0";

  public static void insert (org.omg.CORBA.Any a, EventApp02.EventServer02 that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EventApp02.EventServer02 extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EventApp02.EventServer02Helper.id (), "EventServer02");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EventApp02.EventServer02 read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EventServer02Stub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EventApp02.EventServer02 value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EventApp02.EventServer02 narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EventApp02.EventServer02)
      return (EventApp02.EventServer02)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EventApp02._EventServer02Stub stub = new EventApp02._EventServer02Stub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static EventApp02.EventServer02 unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EventApp02.EventServer02)
      return (EventApp02.EventServer02)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EventApp02._EventServer02Stub stub = new EventApp02._EventServer02Stub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
