package EventApp02;


/**
* EventApp02/EventServer02.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Java/EclipseWorkspace/COMP6231_Project/Event03.idl
* Thursday, March 19, 2020 10:27:37 AM EDT
*/

public interface EventServer02 extends EventServer02Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EventServer02
