package FrontEndApp;


/**
* FrontEndApp/FrontEndServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Java/EclipseWorkspace/COMP6231_Project/FrontEnd.idl
* Monday, March 16, 2020 7:27:45 PM EDT
*/

public interface FrontEndServerOperations 
{
  String sendtoFE (String message);
} // interface FrontEndServerOperations
