package DEMS_FrontEnd;


/**
* DEMS_FrontEnd/DEMSInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/EclipseWorkspace/DEMSCorba/src/FEInterface.idl
* Monday, March 2, 2020 1:54:54 PM EST
*/

abstract public class DEMSInterfaceHelper
{
  private static String  _id = "IDL:DEMS_FrontEnd/DEMSInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, DEMS_FrontEnd.DEMSInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DEMS_FrontEnd.DEMSInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DEMS_FrontEnd.DEMSInterfaceHelper.id (), "DEMSInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DEMS_FrontEnd.DEMSInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DEMSInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DEMS_FrontEnd.DEMSInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DEMS_FrontEnd.DEMSInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DEMS_FrontEnd.DEMSInterface)
      return (DEMS_FrontEnd.DEMSInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DEMS_FrontEnd._DEMSInterfaceStub stub = new DEMS_FrontEnd._DEMSInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DEMS_FrontEnd.DEMSInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DEMS_FrontEnd.DEMSInterface)
      return (DEMS_FrontEnd.DEMSInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DEMS_FrontEnd._DEMSInterfaceStub stub = new DEMS_FrontEnd._DEMSInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
