package DEMS_FrontEnd;


/**
* DEMS_FrontEnd/DEMSInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/EclipseWorkspace/DEMSCorba/src/FEInterface.idl
* Monday, March 2, 2020 1:54:54 PM EST
*/

public interface DEMSInterfaceOperations 
{
  String addEvent (String eventID, String eventType, int bookingCapacity);
  String removeEvent (String eventID, String eventType);
  String listEventAvailability (String eventType);
  String bookEvent (String customerID, String eventID, String eventType);
  String getBookingSchedule (String customerID);
  String cancelEvent (String customerID, String eventID, String eventType);
  String swapEvent (String CustomerID, String newEventID, String newEventType, String oldEventID, String oldEventType);
} // interface DEMSInterfaceOperations
