package DEMS_FrontEnd;


/**
* DEMS_FrontEnd/DEMSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/EclipseWorkspace/DEMSCorba/src/FEInterface.idl
* Monday, March 2, 2020 1:54:54 PM EST
*/

public interface DEMSInterface extends DEMSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DEMSInterface
