package DEMS_FrontEnd;

/**
* DEMS_FrontEnd/DEMSInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/EclipseWorkspace/DEMSCorba/src/FEInterface.idl
* Monday, March 2, 2020 1:54:54 PM EST
*/

public final class DEMSInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public DEMS_FrontEnd.DEMSInterface value = null;

  public DEMSInterfaceHolder ()
  {
  }

  public DEMSInterfaceHolder (DEMS_FrontEnd.DEMSInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DEMS_FrontEnd.DEMSInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DEMS_FrontEnd.DEMSInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DEMS_FrontEnd.DEMSInterfaceHelper.type ();
  }

}
