package EventApp01;

/**
* EventApp01/EventServer01Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Java/EclipseWorkspace/COMP6231_Project/Event01.idl
* Thursday, March 19, 2020 10:15:53 AM EDT
*/

public final class EventServer01Holder implements org.omg.CORBA.portable.Streamable
{
  public EventApp01.EventServer01 value = null;

  public EventServer01Holder ()
  {
  }

  public EventServer01Holder (EventApp01.EventServer01 initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EventApp01.EventServer01Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EventApp01.EventServer01Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EventApp01.EventServer01Helper.type ();
  }

}
