package EventApp01;


/**
* EventApp01/EventServer01Helper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Java/EclipseWorkspace/COMP6231_Project/Event01.idl
* Thursday, March 19, 2020 10:15:53 AM EDT
*/

abstract public class EventServer01Helper
{
  private static String  _id = "IDL:EventApp01/EventServer01:1.0";

  public static void insert (org.omg.CORBA.Any a, EventApp01.EventServer01 that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EventApp01.EventServer01 extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EventApp01.EventServer01Helper.id (), "EventServer01");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EventApp01.EventServer01 read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EventServer01Stub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EventApp01.EventServer01 value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EventApp01.EventServer01 narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EventApp01.EventServer01)
      return (EventApp01.EventServer01)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EventApp01._EventServer01Stub stub = new EventApp01._EventServer01Stub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static EventApp01.EventServer01 unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EventApp01.EventServer01)
      return (EventApp01.EventServer01)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EventApp01._EventServer01Stub stub = new EventApp01._EventServer01Stub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
