package EventApp01;


/**
* EventApp01/EventServer01.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Java/EclipseWorkspace/COMP6231_Project/Event01.idl
* Thursday, March 19, 2020 10:15:53 AM EDT
*/

public interface EventServer01 extends EventServer01Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EventServer01
