package DEMS_FrontEnd;


/**
* DEMS_FrontEnd/DEMSInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/EclipseWorkspace/DistributedProject_FE/src/FEInterface.idl
* Wednesday, March 11, 2020 6:36:11 PM EDT
*/

public interface DEMSInterfaceOperations 
{
  String addEvent (String id, String eventID, String eventType, int bookingCapacity);
  String removeEvent (String id, String eventID, String eventType);
  String listEventAvailability (String id, String eventType);
  String bookEvent (String customerID, String eventID, String eventType);
  String getBookingSchedule (String customerID);
  String cancelEvent (String customerID, String eventID, String eventType);
  String swapEvent (String CustomerID, String newEventID, String newEventType, String oldEventID, String oldEventType);
} // interface DEMSInterfaceOperations
