package DEMS_FrontEnd;


/**
* DEMS_FrontEnd/DEMSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/EclipseWorkspace/DistributedProject_FE/src/FEInterface.idl
* Wednesday, March 11, 2020 6:36:11 PM EDT
*/

public interface DEMSInterface extends DEMSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DEMSInterface
